### ISSUE TITLE
Losing my mind not being able to debug

### ISSUE THREAD

**Issue by m4heshd** [branchseer/DeskGap#44]
Hi @patr0nus,

First of all, this project is a god given to all of us because I'm so sick of shipping GUIs that has a single button and 80+ MBs when packed. Electron really is great but rarely practical. I really appreciate the work you have done. Your framework is the only functional lightweight one that's out there.

But I'm having so much trouble not being able to debug either of the instances (Webview and Node). I'm on Windows 10 build 18363. The app simply doesn't show up on devtools. 

![image](https://user-images.githubusercontent.com/6711514/71314601-30fcce00-2471-11ea-882c-ff7c2123cbab.png)

And for the node process, `--inspect` doesn't work and there's no way to attach a debugger or get any kind of an output. I saw somebody else have mentioned this in https://github.com/patr0nus/DeskGap/issues/22#issuecomment-543647164 too. Trying to get this very urgent project up and running but can't go on blindly. I also have no idea how to have other node modules running when distributed inside the app directory.

I would really love it if you can give me some insight on how to get this up and running.

**Comment by m4heshd** [comment]
pinging @patr0nus. Any response would be appreciated.

**Comment by patr0nus** [comment]
@m4heshd Hi,

The Edge DevTools should work. Are you sure DeskGap are using EdgeHTML? The EdgeHTML webview won't work if the process has the admin rights. In this case DeskGap will fallback to the Trident(IE) engine.

**Comment by m4heshd** [comment]
Thank you for the response. How can i make sure It's running EdgeHTML and how to check which one it's running? Also please guide me on how to debug the main process (The node process)

**Comment by patr0nus** [comment]
@m4heshd 

You can use `document.write(navigator.userAgent)` in your browser script to check the user agent which tells what engine is running.

And there is `require('deskgap').WebViews.getDefaultEngine()` in Node, but for now it's not useful because `console.log` doesn't seem to work on Windows. I am looking into this bug.

DeskGap doesn't expose a way to debug Node scripts. I will try to add this functionality.

**Comment by m4heshd** [comment]
Thank you for clearing this up. Then i guess for the moment i can go with express, socket.io and just load that on DeskGap. One more little thing. How can i load the 3rd party modules on my project when I'm distributing inside the `resources/app` directory?
